<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class BreadsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('breads')->delete();

        \DB::table('breads')->insert(array(
            0 =>
                array(
                    'id' => 1,
                    'specie_id' => 1,
                    'name' => 'German Shepherd',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            1 =>
                array(
                    'id' => 2,
                    'specie_id' => 1,
                    'name' => 'Bulldog',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            2 =>
                array(
                    'id' => 3,
                    'specie_id' => 1,
                    'name' => 'Labrador Retriever',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            3 =>
                array(
                    'id' => 4,
                    'specie_id' => 1,
                    'name' => 'Golden Retriever',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            4 =>
                array(
                    'id' => 5,
                    'specie_id' => 1,
                    'name' => 'French Bulldog',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            5 =>
                array(
                    'id' => 6,
                    'specie_id' => 1,
                    'name' => 'Siberian Husky',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            6 =>
                array(
                    'id' => 7,
                    'specie_id' => 1,
                    'name' => 'Beagle',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            7 =>
                array(
                    'id' => 8,
                    'specie_id' => 1,
                    'name' => 'Poodle',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            8 =>
                array(
                    'id' => 9,
                    'specie_id' => 1,
                    'name' => 'Chihuahua',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            9 =>
                array(
                    'id' => 10,
                    'specie_id' => 1,
                    'name' => 'Dachshund',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            10 =>
                array(
                    'id' => 11,
                    'specie_id' => 1,
                    'name' => 'Border Collie',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            11 =>
                array(
                    'id' => 12,
                    'specie_id' => 1,
                    'name' => 'Rottweiler',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            12 =>
                array(
                    'id' => 13,
                    'specie_id' => 1,
                    'name' => 'Bichon Frise',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            13 =>
                array(
                    'id' => 14,
                    'specie_id' => 1,
                    'name' => 'Australian Shepherd',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            14 =>
                array(
                    'id' => 15,
                    'specie_id' => 1,
                    'name' => 'Airedale Terrier',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            15 =>
                array(
                    'id' => 16,
                    'specie_id' => 1,
                    'name' => 'Affenpinscher',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            16 =>
                array(
                    'id' => 17,
                    'specie_id' => 1,
                    'name' => 'Maltese',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            17 =>
                array(
                    'id' => 18,
                    'specie_id' => 1,
                    'name' => 'English Cocker Spaniel',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            18 =>
                array(
                    'id' => 19,
                    'specie_id' => 1,
                    'name' => 'Chow Chow',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            19 =>
                array(
                    'id' => 20,
                    'specie_id' => 1,
                    'name' => 'Pomeranian',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            20 =>
                array(
                    'id' => 21,
                    'specie_id' => 1,
                    'name' => 'American Eskimo',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            21 =>
                array(
                    'id' => 22,
                    'specie_id' => 1,
                    'name' => 'Cavalier King Charles',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            22 =>
                array(
                    'id' => 23,
                    'specie_id' => 1,
                    'name' => 'Yorkshire Terrier',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            23 =>
                array(
                    'id' => 24,
                    'specie_id' => 1,
                    'name' => 'Anatolian Shepherd',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            24 =>
                array(
                    'id' => 25,
                    'specie_id' => 1,
                    'name' => 'Pembroke Welsh Corgi',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            25 =>
                array(
                    'id' => 26,
                    'specie_id' => 1,
                    'name' => 'Basset Hound',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            26 =>
                array(
                    'id' => 27,
                    'specie_id' => 1,
                    'name' => 'New found land',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            27 =>
                array(
                    'id' => 28,
                    'specie_id' => 1,
                    'name' => 'Basenji',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            28 =>
                array(
                    'id' => 29,
                    'specie_id' => 1,
                    'name' => 'Havanese',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            29 =>
                array(
                    'id' => 30,
                    'specie_id' => 1,
                    'name' => 'Belgian Malinois',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            30 =>
                array(
                    'id' => 31,
                    'specie_id' => 1,
                    'name' => 'Boston Terrier',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            31 =>
                array(
                    'id' => 32,
                    'specie_id' => 1,
                    'name' => 'Cairn Terrier',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            32 =>
                array(
                    'id' => 33,
                    'specie_id' => 1,
                    'name' => 'Bullmastiff',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            33 =>
                array(
                    'id' => 34,
                    'specie_id' => 1,
                    'name' => 'Brittany',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            34 =>
                array(
                    'id' => 35,
                    'specie_id' => 1,
                    'name' => 'Sheltie',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            35 =>
                array(
                    'id' => 36,
                    'specie_id' => 1,
                    'name' => 'Black Russian Terrier',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            36 =>
                array(
                    'id' => 37,
                    'specie_id' => 1,
                    'name' => 'Bedlington Terrier',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            37 =>
                array(
                    'id' => 38,
                    'specie_id' => 1,
                    'name' => 'American Pit Bull Terrie',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            38 =>
                array(
                    'id' => 39,
                    'specie_id' => 1,
                    'name' => 'Dobermann',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            39 =>
                array(
                    'id' => 40,
                    'specie_id' => 1,
                    'name' => 'Shiba Inu',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            40 =>
                array(
                    'id' => 41,
                    'specie_id' => 1,
                    'name' => 'Samoyed',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            41 =>
                array(
                    'id' => 42,
                    'specie_id' => 1,
                    'name' => 'Sarabi',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            42 =>
                array(
                    'id' => 43,
                    'specie_id' => 1,
                    'name' => 'American Bully',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            43 =>
                array(
                    'id' => 44,
                    'specie_id' => 1,
                    'name' => 'Jack Russell Terrier',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            44 =>
                array(
                    'id' => 45,
                    'specie_id' => 1,
                    'name' => 'Borzoi',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            45 =>
                array(
                    'id' => 46,
                    'specie_id' => 1,
                    'name' => 'Maltipoo',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            46 =>
                array(
                    'id' => 47,
                    'specie_id' => 1,
                    'name' => 'Goldendoodle',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            47 =>
                array(
                    'id' => 48,
                    'specie_id' => 1,
                    'name' => 'Akita Inu',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            48 =>
                array(
                    'id' => 49,
                    'specie_id' => 2,
                    'name' => 'Siamese',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            49 =>
                array(
                    'id' => 50,
                    'specie_id' => 2,
                    'name' => 'British Shorthair',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            50 =>
                array(
                    'id' => 51,
                    'specie_id' => 2,
                    'name' => 'Maine Coon',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            51 =>
                array(
                    'id' => 52,
                    'specie_id' => 2,
                    'name' => 'Persian',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            52 =>
                array(
                    'id' => 53,
                    'specie_id' => 2,
                    'name' => 'Ragdoll',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            53 =>
                array(
                    'id' => 54,
                    'specie_id' => 2,
                    'name' => 'Sphynx',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            54 =>
                array(
                    'id' => 55,
                    'specie_id' => 2,
                    'name' => 'American Shorthair',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            55 =>
                array(
                    'id' => 56,
                    'specie_id' => 2,
                    'name' => 'Abyssinian',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            56 =>
                array(
                    'id' => 57,
                    'specie_id' => 2,
                    'name' => 'Exotic Shorthair',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            57 =>
                array(
                    'id' => 58,
                    'specie_id' => 2,
                    'name' => 'Scottish Fold',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            58 =>
                array(
                    'id' => 59,
                    'specie_id' => 2,
                    'name' => 'Burmese',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            59 =>
                array(
                    'id' => 60,
                    'specie_id' => 2,
                    'name' => 'Birman',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            60 =>
                array(
                    'id' => 61,
                    'specie_id' => 2,
                    'name' => 'Bombay',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            61 =>
                array(
                    'id' => 62,
                    'specie_id' => 2,
                    'name' => 'Siberian',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            62 =>
                array(
                    'id' => 63,
                    'specie_id' => 2,
                    'name' => 'Norwegian Forest',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            63 =>
                array(
                    'id' => 64,
                    'specie_id' => 2,
                    'name' => 'Munchkin',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            64 =>
                array(
                    'id' => 65,
                    'specie_id' => 2,
                    'name' => 'American Curl',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            65 =>
                array(
                    'id' => 66,
                    'specie_id' => 2,
                    'name' => 'Russian Blue',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            66 =>
                array(
                    'id' => 67,
                    'specie_id' => 2,
                    'name' => 'American Bobtail',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            67 =>
                array(
                    'id' => 68,
                    'specie_id' => 2,
                    'name' => 'Devon Rex',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            68 =>
                array(
                    'id' => 69,
                    'specie_id' => 2,
                    'name' => 'Balinese',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            69 =>
                array(
                    'id' => 70,
                    'specie_id' => 2,
                    'name' => 'Oriental Shorthair',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            70 =>
                array(
                    'id' => 71,
                    'specie_id' => 2,
                    'name' => 'Chartreux',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            71 =>
                array(
                    'id' => 72,
                    'specie_id' => 2,
                    'name' => 'Japanese Bobtail',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            72 =>
                array(
                    'id' => 73,
                    'specie_id' => 2,
                    'name' => 'Manx',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            73 =>
                array(
                    'id' => 74,
                    'specie_id' => 2,
                    'name' => 'Turkish Angora',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            74 =>
                array(
                    'id' => 75,
                    'specie_id' => 2,
                    'name' => 'Ragamuffin',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            75 =>
                array(
                    'id' => 76,
                    'specie_id' => 2,
                    'name' => 'Egyptian Mau',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            76 =>
                array(
                    'id' => 77,
                    'specie_id' => 2,
                    'name' => 'Somali',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            77 =>
                array(
                    'id' => 78,
                    'specie_id' => 2,
                    'name' => 'Himalayan',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            78 =>
                array(
                    'id' => 79,
                    'specie_id' => 2,
                    'name' => 'Cornish Rex',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            79 =>
                array(
                    'id' => 80,
                    'specie_id' => 2,
                    'name' => 'Selkirk Rex',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            80 =>
                array(
                    'id' => 81,
                    'specie_id' => 2,
                    'name' => 'Singapura',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            81 =>
                array(
                    'id' => 82,
                    'specie_id' => 2,
                    'name' => 'Korat',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            82 =>
                array(
                    'id' => 83,
                    'specie_id' => 2,
                    'name' => 'Ocicat',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            83 =>
                array(
                    'id' => 84,
                    'specie_id' => 2,
                    'name' => 'Tonkinese',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            84 =>
                array(
                    'id' => 85,
                    'specie_id' => 2,
                    'name' => 'Turkish Van',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            85 =>
                array(
                    'id' => 86,
                    'specie_id' => 2,
                    'name' => 'British Longhair',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            86 =>
                array(
                    'id' => 87,
                    'specie_id' => 2,
                    'name' => 'Havana Brown',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            87 =>
                array(
                    'id' => 88,
                    'specie_id' => 2,
                    'name' => 'LaPerm',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            88 =>
                array(
                    'id' => 89,
                    'specie_id' => 2,
                    'name' => 'Chausie',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            89 =>
                array(
                    'id' => 90,
                    'specie_id' => 2,
                    'name' => 'Burmilla',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            90 =>
                array(
                    'id' => 91,
                    'specie_id' => 2,
                    'name' => 'Snowshoe',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            91 =>
                array(
                    'id' => 92,
                    'specie_id' => 2,
                    'name' => 'Lykoi',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            92 =>
                array(
                    'id' => 93,
                    'specie_id' => 2,
                    'name' => 'Toyger',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            93 =>
                array(
                    'id' => 94,
                    'specie_id' => 2,
                    'name' => 'Colorpoint Shorthair',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            94 =>
                array(
                    'id' => 95,
                    'specie_id' => 2,
                    'name' => 'Sokoke',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            95 =>
                array(
                    'id' => 96,
                    'specie_id' => 2,
                    'name' => 'Javanese',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            96 =>
                array(
                    'id' => 97,
                    'specie_id' => 2,
                    'name' => 'Australian Mist',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            97 =>
                array(
                    'id' => 98,
                    'specie_id' => 2,
                    'name' => 'Khao Manee',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            98 =>
                array(
                    'id' => 99,
                    'specie_id' => 3,
                    'name' => 'African Wild Dog',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            99 =>
                array(
                    'id' => 100,
                    'specie_id' => 3,
                    'name' => 'Azawakh',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            100 =>
                array(
                    'id' => 101,
                    'specie_id' => 3,
                    'name' => 'Australian Dingo',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            101 =>
                array(
                    'id' => 102,
                    'specie_id' => 3,
                    'name' => 'Bergamasco',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            102 =>
                array(
                    'id' => 103,
                    'specie_id' => 3,
                    'name' => 'Jackal',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            103 =>
                array(
                    'id' => 104,
                    'specie_id' => 3,
                    'name' => 'Bush Dog',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            104 =>
                array(
                    'id' => 105,
                    'specie_id' => 3,
                    'name' => 'Coyote',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            105 =>
                array(
                    'id' => 106,
                    'specie_id' => 3,
                    'name' => 'Dandie Dinmont Terrier',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            106 =>
                array(
                    'id' => 107,
                    'specie_id' => 3,
                    'name' => 'Rhodesian Ridgeback',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            107 =>
                array(
                    'id' => 108,
                    'specie_id' => 3,
                    'name' => 'Tibetan Mastiff',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            108 =>
                array(
                    'id' => 109,
                    'specie_id' => 3,
                    'name' => 'Wolf',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            109 =>
                array(
                    'id' => 110,
                    'specie_id' => 3,
                    'name' => 'Arctic Fox',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            110 =>
                array(
                    'id' => 111,
                    'specie_id' => 3,
                    'name' => 'Asiatic Wild Dog',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            111 =>
                array(
                    'id' => 112,
                    'specie_id' => 3,
                    'name' => 'Basenji',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            112 =>
                array(
                    'id' => 113,
                    'specie_id' => 3,
                    'name' => 'Borzoi',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            113 =>
                array(
                    'id' => 114,
                    'specie_id' => 3,
                    'name' => 'Chinese Crested Dog',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            114 =>
                array(
                    'id' => 115,
                    'specie_id' => 3,
                    'name' => 'Coton de Tulear',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            115 =>
                array(
                    'id' => 116,
                    'specie_id' => 3,
                    'name' => 'Fox',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            116 =>
                array(
                    'id' => 117,
                    'specie_id' => 3,
                    'name' => 'Leon Berger',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            117 =>
                array(
                    'id' => 118,
                    'specie_id' => 3,
                    'name' => 'Raccoon Dog',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            118 =>
                array(
                    'id' => 119,
                    'specie_id' => 3,
                    'name' => 'Sloughi',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            119 =>
                array(
                    'id' => 120,
                    'specie_id' => 3,
                    'name' => 'Xoloitzcuintli',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            120 =>
                array(
                    'id' => 121,
                    'specie_id' => 4,
                    'name' => 'Jungle Cat',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            121 =>
                array(
                    'id' => 122,
                    'specie_id' => 4,
                    'name' => 'Caracal',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            122 =>
                array(
                    'id' => 123,
                    'specie_id' => 4,
                    'name' => 'Iberian Lynx',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            123 =>
                array(
                    'id' => 124,
                    'specie_id' => 4,
                    'name' => 'Bengal',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            124 =>
                array(
                    'id' => 125,
                    'specie_id' => 4,
                    'name' => 'Leopard',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            125 =>
                array(
                    'id' => 126,
                    'specie_id' => 4,
                    'name' => 'Serval',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            126 =>
                array(
                    'id' => 127,
                    'specie_id' => 4,
                    'name' => 'Fishing Cat',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            127 =>
                array(
                    'id' => 128,
                    'specie_id' => 4,
                    'name' => 'Abyssinian',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            128 =>
                array(
                    'id' => 129,
                    'specie_id' => 4,
                    'name' => 'Asian Leopard Cat',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            129 =>
                array(
                    'id' => 130,
                    'specie_id' => 4,
                    'name' => 'Bobcats',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            130 =>
                array(
                    'id' => 131,
                    'specie_id' => 4,
                    'name' => 'Ocelot',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            131 =>
                array(
                    'id' => 132,
                    'specie_id' => 4,
                    'name' => 'Egyptian Mau',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            132 =>
                array(
                    'id' => 133,
                    'specie_id' => 4,
                    'name' => 'Siberian',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            133 =>
                array(
                    'id' => 134,
                    'specie_id' => 4,
                    'name' => 'African Golden Cat',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            134 =>
                array(
                    'id' => 135,
                    'specie_id' => 4,
                    'name' => 'Savannahs Cat',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            135 =>
                array(
                    'id' => 136,
                    'specie_id' => 4,
                    'name' => 'Snow Leopard',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            136 =>
                array(
                    'id' => 137,
                    'specie_id' => 4,
                    'name' => 'Tiger',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            137 =>
                array(
                    'id' => 138,
                    'specie_id' => 4,
                    'name' => 'British Shorthair',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            138 =>
                array(
                    'id' => 139,
                    'specie_id' => 4,
                    'name' => 'Jaguarundi',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            139 =>
                array(
                    'id' => 140,
                    'specie_id' => 4,
                    'name' => 'Marbled Cat',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            140 =>
                array(
                    'id' => 141,
                    'specie_id' => 4,
                    'name' => 'Ocicat',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            141 =>
                array(
                    'id' => 142,
                    'specie_id' => 4,
                    'name' => 'Ragdoll',
                    'image' => NULL,
                    'added_by' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
        ));
    }
}