<?php

namespace Database\Seeders;

use App\Models\Breed;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class BreedsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('breeds')->truncate();

        //Canine(Dogs)
        $dogBreeds = [
            'Abruzzenhumk',
            'Affenpinscher',
            'Afghan Hound',
            'Airedale Terrier',
            'Akbash',
            'Akita',
            'Akita Inu',
            'Akita Mix',
            'Alangu Mastiff',
            'Alano Espanol',
            'Alapaha Blue Blood Bulldog',
            'Alaskan Husky',
            'Alaska Klee Kai',
            'Alaskan Malamute',
            'Alopekis',
            'Alpine Dachsbracke',
            'American Akita',
            'American Bandogge',
            'American Bulldog',
            'American Bull Terrier',
            'American Cattle Dog',
            'American Cocker Spaniel',
            'American English Coonhound',
            'American Eskimo',
            'American Eskimo, Miniature',
            'American Foxhound',
            'American Hairless Terrier',
            'American Staffordshire Terrier',
            'American Staghound',
            'American Water Spaniel',
            'Anatolian Shepherd',
            'Anglo',
            'Appenzeller Mountain Dog',
            'Arctic Husky',
            'Argentine Dogo',
            'Ariegeois',
            'Armant',
            'Armenian Gampr',
            'Artois Hound',
            'Australian Cattle Dog',
            'Australian Kelpie',
            'Australian Koolie',
            'Australian Labradoodle',
            'Australian Poodle',
            'Australian Shepherd',
            'Australian Shepherd Mix',
            'Australian Shepherd, Miniature',
            'Australian Silky Terrier',
            'Australian Terrier',
            'Austrian Black and Tan Hound',
            'Azawakh',
            'Bakharwal Dog',
            'Balkan Hound',
            'Banjara Mastiff',
            'Bantam Bulldog',
            'Barbet',
            'Basenji',
            'Basenji Mix',
            'Basque Shepherd Dog',
            'Basset Artesien Normand',
            'Basset Bleu de Gascogne',
            'Basset Fauve de Bretagne',
            'Basset Griffon Vandeen',
            'Basset Hound',
            'Bavarian Mountain Hound',
            'Beagle',
            'Beagle Mix',
            'Bearded Collie',
            'Bearded Tibetan Mastiff',
            'Beauceron',
            'Bedlington Terrier',
            'Belgian Griffon',
            'Belgian Groenendael',
            'Belgian Laekenois',
            'Belgian Malinois',
            'Belgian Sheepdog',
            'Belgian Shepherd',
            'Belgian Tervuren',
            'Bergamasco',
            'Berger Blanc Suisse',
            'Berger des Pyrenees',
            'Berger Picard',
            'Bernedoodle',
            'Bernese Mountain Dog',
            'Bhotia',
            'Bichon Frise',
            'Bichon Frise Mix',
            'Biewer',
            'Bisben',
            'Black Norwegian Elkhound',
            'Black and Tan Coonhound',
            'Black Russian Terrier',
            'Blackmouth Cur',
            'Bloodhound',
            'Blue Heeler',
            'Blue Lacy',
            'Blue Paul Terrier',
            'Blue Picardy Spaniel',
            'Blue Tick Hound',
            'Bluetick Coonhound',
            'Boerboel',
            'Bohemian Shepherd',
            'Bolognese',
            'Bolonka',
            'Border Collie',
            'Border Collie Mix',
            'Border Terrier',
            'Borzoi',
            'Bosnian Coarse Haired Hound',
            'Bosnian Mountain Dog',
            'Boston Terrier',
            'Bouvier Bernois',
            'Bouvier des Ardennes',
            'Bouvier des Flandres',
            'Boxer',
            'Boxer Mix',
            'Boykin Spaniel',
            'Bracco Italiano',
            'Braque d’Auvergne',
            'Braque du Bourbonnais',
            'Braque Francais',
            'Braque Saint',
            'Brazilian Mastiff',
            'Brazilian Terrier',
            'Briard',
            'Briquet Griffon Vendeen',
            'British White Retriever',
            'Brittany Spaniel',
            'Broholmer',
            'Brussels Griffon',
            'Bucovina',
            'Bulgarian Shepherd Dog',
            'Bull Arab',
            'Bull Terrier',
            'Bullmastiff',
            'Bully Kutta',
            'Byelorussian Ovcharka',
            'Ca de Bou',
            'Cabecudo Boiadeiro',
            'Cairn Terrier',
            'Canaan Dog',
            'Canadian Eskimo Dog',
            'Canadian Pointer',
            'Cane Corso',
            'Canine, Other',
            'Cardigan Welsh Corgi',
            'Carlin Pinscher',
            'Carolina Dog',
            'Carpathian Shepherd Dog',
            'Carpatin',
            'Catahoula Bulldog',
            'Catahoula Leopard Dog',
            'Catalan Sheepdog',
            'Cattle Dog',
            'Cattle Dog Mix',
            'Caucasian Ovcharka',
            'Caucasian Shepherd',
            'Cavachon',
            'Cavalier King Charles Spaniel',
            'Cavalier Mix',
            'Cavapoo',
            'Cavapom',
            'Central Asian Shepherd',
            'Cesky Fousek',
            'Cesky Terrier',
            'Chart Polski',
            'Chesapeake Bay Retriever',
            'Chihuahua',
            'Chihuahua Mix',
            'Chilean Fox Terrier',
            'Chindo',
            'Chinese Chongquing Dog',
            'Chinese Crested',
            'Chinese Crested Mix',
            'Chinese Foo Dog',
            'Chinese Shar-Pei',
            'Chinook',
            'Chipoo',
            'Chiweenie',
            'Chippiparai',
            'Chorkie',
            'Chow Chow',
            'Chow Mix',
            'Ciobanesc de Bucovina',
            'Cirassian Orloff Wolfhound',
            'Cirneco dell Etna',
            'Clumber Spaniel',
            'Cockapoo',
            'Cocker Spaniel',
            'Cocker Spaniel Mix',
            'Collie',
            'Corgi',
            'Corgi Mix',
            'Coton du Tulear',
            'Croatian Mountain Dog',
            'Croatian Sheepdog',
            'Cur',
            'Curly Coated Retriever',
            'Czech Shepard',
            'Czechoslovakian Wolfdog',
            'Dachshund',
            'Dachshund, Miniature',
            'Dachshund, Miniature Longhair',
            'Dachshund, Standard',
            'Dachshund, Longhair',
            'Dachshund, Wirehair',
            'Dachshund Mix',
            'Dalmatian',
            'Dandie Dinmont Terrier',
            'Deerhound',
            'Dingo',
            'Doberman Pinscher',
            'Doberman Pinscher Mix',
            'Dogo Argentino',
            'Dogo Cubano',
            'Dogue de Bordeaux',
            'Drahthaar',
            'Dutch Shepherd',
            'East European Shepherd',
            'Elkhound',
            'Elo',
            'English Bull Terrier',
            'English Bulldog',
            'English Cocker Spaniel',
            'English Coonhound',
            'English Foxhound',
            'English Labrador',
            'English Mastiff',
            'English Pointer',
            'English Retriever',
            'English Setter',
            'English Shepherd',
            'English Springer Spaniel',
            'English Staffordshire Terrier',
            'English Toy Spaniel',
            'English Toy Terrier',
            'English White Terrier',
            'Entlebucher Mountain Dog',
            'Entlebucher Sennenhund',
            'Estonian Hound',
            'Estrela Mountain Dog',
            'Eurasier',
            'Feist',
            'Fell Terrier',
            'Field Spaniel',
            'Fila Brasileiro',
            'Finnish Hound',
            'Finnish Lapphund',
            'Finnish Spitz',
            'Flat Coated Retriever',
            'Fox Hound',
            'Fox Terrier',
            'French Brittany',
            'French Bulldog',
            'French Bulldog Mix',
            'French Mastiff',
            'French Spaniel',
            'Galgo Espanol',
            'German Longhaired Pointer',
            'German Pinscher',
            'German Rough-Haired Pointer',
            'German Shepherd',
            'German Shepherd Mix',
            'German Shorthaired Pointer',
            'German Spaniel',
            'German Spitz',
            'German Wirehaired Pointer',
            'Giant Schnauzer',
            'Glen of Imaal Terrier',
            'Golden Mountain Dog',
            'Golden Retriever',
            'Golden Retriever Mix',
            'Goldendoodle',
            'Gordon Setter',
            'Grand Basset Griffon Vendeen',
            'Great Dane',
            'Great Dan Mix',
            'Great Pyrenees',
            'Greater Swiss Mountain Dog',
            'Greyhound',
            'Greyhound Mix',
            'Griffon',
            'Groenendael',
            'Hanover Hound',
            'Harlequin Pinscher',
            'Harrier',
            'Havanese',
            'Havanese Mix',
            'Hawaiian Poi Dog',
            'Heading Dog',
            'Heeler',
            'Heeler Mix',
            'Hermes Bulldog',
            'Himalayan Mastiff',
            'Himalayan Sheepdog',
            'Holland Shepherd',
            'Hollandse Herder',
            'Hound',
            'Hound Mix',
            'Husky',
            'Husky Mix',
            'Ibizan Hound',
            'Icelandic Sheepdog',
            'Indian Bull Terrier',
            'Indian Spitz',
            'Inuit',
            'Irish Bull Terrier',
            'Irish Red and White Setter',
            'Irish Setter',
            'Irish Staffordshire Terrier',
            'Irish Terrier',
            'Irish Water Spaniel',
            'Irish Wolfhound',
            'Italian Greyhound',
            'Italian Mastiff',
            'Italian Spinone',
            'Italian Volpino',
            'Jack Russell Terrier',
            'Jack Russell, Wirehair',
            'Japanese Akita',
            'Japanese Chin',
            'Japanese Mastiff',
            'Japanese Spitz',
            'Japanese Terrier',
            'Jindo',
            'Keeshond',
            'Kelpie',
            'Kerry Beagle',
            'Kerry Blue Terrier',
            'King Shepherd',
            'Kishu',
            'Komondor',
            'Kooikerhondje',
            'Koolie',
            'Korean Jindo',
            'Korean Mastiff',
            'Kuvaszok',
            'Labradoodle',
            'Labrador Retriever',
            'Labrador Retriever Mix',
            'Labrador Mix',
            'Laekenois',
            'Lagotto Romagnolo',
            'Lakeland Terrier',
            'Lancaster Heeler',
            'Landseer',
            'Large Munsterlander',
            'Latvian Hound',
            'Leonberger',
            'Lhasa Apso',
            'Lhasa Apso Mix',
            'Lithuanian Hound',
            'Llewellyn Setter',
            'Longdog',
            'Lowchen',
            'Lucas Terrier',
            'Lurcher',
            'Maltese',
            'Maltese Mix',
            'Maltipoo',
            'Manchester Terrier',
            'Mastiff',
            'Mastiff Mix',
            'McNab',
            'Mexican Hairless Dog',
            'Miniature American Eskimo',
            'Miniature Australian Shepherd',
            'Miniature Bull Terrier',
            'Miniature Dachshund',
            'Miniature Fox Terrier',
            'Miniature Goldendoodle',
            'Miniature Pinscher',
            'Miniature Poodle',
            'Miniature Schnauzer',
            'Mixed Breed',
            'Morkie',
            'Mountain Cur',
            'Mountain Dog',
            'Mountain Feist',
            'Munsterlander',
            'Native American Indian Dog',
            'Neapolitan Mastiff',
            'Nebolish Mastiff',
            'Newfoundland',
            'Norfolk Terrier',
            'Norwegian Buhunden',
            'Norwegian Elkhound',
            'Norwegian Lundehunden',
            'Norwich Terrier',
            'Nova Scotia Duck Tolling Retriever',
            'Olde English Bulldogge',
            'Old Danish Pointer',
            'Old English Sheepdog',
            'Old English Terrier',
            'Other',
            'Otterhound',
            'Papillon',
            'Papillon Mix',
            'Parson Russell Terrier',
            'Peke-a-poo',
            'Pekingese',
            'Pembroke Welsh Corgi',
            'Perro de Presa Canario',
            'Peruvian Hairless Dog',
            'Peruvian Inca Orchids',
            'Petit Basset Griffon Vendeen',
            'Petit Berger',
            'Petit Bleu de Gascogne',
            'Petit Brabancon',
            'Petite Basset',
            'Pharaoh Hound',
            'Picardy Shepherd',
            'Picardy Spaniel',
            'Pit Bull',
            'Pit Bull Mix',
            'Pit Bull, American',
            'Plott Hound',
            'Pocket Pit Bull Terrier',
            'Pointer',
            'Pointer Mix',
            'Polish Lowland Sheepdog',
            'Polish Sheepdog',
            'Pomeranian',
            'Pomeranian Mix',
            'Poodle',
            'Poodle, Standard',
            'Poodle, Miniature',
            'Poodle, Tea Cup',
            'Poodle, Toy',
            'Poodle Mix',
            'Portuguese Podengo',
            'Portuguese Pointer',
            'Portuguese Shepherd Dog',
            'Portuguese Water Dog',
            'Portuguese Water Hound',
            'Pugapoo',
            'Puggle',
            'Pug',
            'Pug Mix',
            'Puli',
            'Pyrenean Mastiff',
            'Pyrenean Mountain Dog',
            'Pyrenean Shepherd',
            'Queensland Heeler',
            'Rat Terrier',
            'Redbone Coonhound',
            'Red Bone Hound',
            'Red Heeler',
            'Retriever Mix',
            'Retreiver',
            'Rhodesian Ridgeback',
            'Rhodesian Ridgeback Mix',
            'Rottweiler',
            'Rottweiler Mix',
            'Rough Collie',
            'Russell Terrier',
            'Russian European Laika',
            'Russian Hound',
            'Russian Setter',
            'Russian Spaniel',
            'Russian Toy Terrier',
            'Saint Bernard',
            'St. Bernard',
            'Saluki',
            'Samoyed',
            'Sanshu',
            'Schipperke',
            'Schnauzer',
            'Schnauzer Mix',
            'Schnoodle',
            'Scottish Deerhound',
            'Scottish Terrier',
            'Sealyham Terrier',
            'Serbian Hound',
            'Setter Mix',
            'Shar Pei',
            'Shar Pei Mix',
            'Sheep Dog',
            'Sheepadoodle',
            'Shepherd',
            'Shepherd Mix',
            'Shetland Sheepdog',
            'Shiba Inu',
            'Shiba Inu Mix',
            'Shih Tzu',
            'Shih Tzu Mix',
            'Shih-Poo',
            'Shiloh Shepherd',
            'Siberian Husky',
            'Silken Windhound',
            'Silky Terrier',
            'Skye Terrier',
            'Sloughi',
            'Slovakian Hound',
            'Small Munsterlander',
            'Smooth Coated Collie',
            'Smooth Fox Terrier',
            'Soft Coated Wheaten Terrier',
            'South African Boerboel',
            'Spaniel Mix',
            'Spanish Greyhound',
            'Spanish Mastiff',
            'Spanish Water Dog',
            'Spanish Pointer',
            'Spinone Italiano',
            'Spitz',
            'Springer Spaniel',
            'Staffordshire Bull Terrier',
            'Standard Schnauzer',
            'Standard Poodle',
            'Sussex Spaniel',
            'Swedish Elkhound',
            'Swedish Lapphund',
            'Swedish Vallhund',
            'Taigan',
            'Tainaker',
            'Terrier',
            'Terrier Mix',
            'Tervuren',
            'Thai Ridgeback',
            'Thai Hairless Dog',
            'Tibetan Mastiff',
            'Tibetan Spaniel',
            'Tibetan Terrier',
            'Tosa Ken',
            'Toy Fox Terrier',
            'Toy Manchester Terrier',
            'Toy Poodle',
            'Treeing Cur',
            'Treeing Feist',
            'Treeing Walker Coonhound',
            'Turkish Kangal',
            'Vizsla',
            'Vizsla Mix',
            'Volpino',
            'Walker Hound',
            'Weimaraner',
            'Welsh Springer Spaniel',
            'Welsh Terrier',
            'West Highland White Terrier',
            'Wheaton Terrier',
            'Whippet',
            'White Shepherd',
            'Wire Fox Terrier',
            'Wirehaired Pointing Griffon',
            'Windsprite',
            'Wolfhound',
            'Wolfhound, Irish',
            'Wolf Hybrid',
            'Xoloitzquintli',
            'Yorkipoo',
            'Yorkshire Terrier',
            'Yorkie Mix'
        ];

        foreach ($dogBreeds as $dogBreed){
            $canine = new Breed;
            $canine->specie_id = 1;
            $canine->name = $dogBreed;
            $canine->added_by = 1;
            $canine->save();
        }

        //Feline(Cats)
        $catBreeds = [
            'Abyssinian',
            'Aegean',
            'American Bobtail',
            'American Curl',
            'American Long Hair',
            'American Polydactyl',
            'American Short Hair',
            'American Wirehair',
            'Angora',
            'Asian Semi-Longhair',
            'Australian Mist',
            'Balinese',
            'Bengal',
            'Bengal Mix',
            'Birman',
            'Bobcat',
            'Bombay',
            'Brazilian Shorthair',
            'British Blue',
            'British Longhair',
            'British Shorthair',
            'Burmese',
            'Burmilla',
            'Calico',
            'California Spangled Cat',
            'Chantilly/Tiffany Cat',
            'Chartreux',
            'Colorpoint Shorthair',
            'Chausie',
            'Cornish Rex',
            'Cymric',
            'Devon Rex',
            'Domestic Dwarf',
            'Domestic Short Hair',
            'Domestic Medium Hair',
            'Domestic Long Hair',
            'Egyptian Mau',
            'English Shorthair',
            'European Shorthair',
            'Exotic Short Hair',
            'Feline Mixed Breed',
            'German Rex',
            'Havana Brown',
            'Highland Cat',
            'Himalayan',
            'Himalayan Mix',
            'Ichabod',
            'Japanese Bobtail',
            'Javanese',
            'Keetso',
            'Korat',
            'LaPerm',
            'Lynx',
            'Maine Coon',
            'Maine Coon Mix',
            'Manx',
            'Munchkin',
            'Nebelung',
            'Norwegian Forest Cat',
            'Ocicat',
            'Ojos Azules',
            'Oriental Longhair',
            'Oriental Shorthair',
            'Other Feline',
            'Panthera Tigris',
            'Perrsian',
            'Persian Mix',
            'Peterbald',
            'Pixie-bob',
            'Ragamuffin',
            'Ragdoll',
            'Ragdoll Mix',
            'Russian',
            'Russian Blue',
            'Russian Blue Mix',
            'Savannah',
            'Scottish Fold',
            'Scottish Straight',
            'Seal Point',
            'Selkirk Rex',
            'Serval',
            'Siamese',
            'Siamese Mix',
            'Siberian',
            'Singapura',
            'Snowshoe',
            'Sokoke',
            'Somali',
            'Sphynx',
            'Thai',
            'Tonkinese',
            'Toyger',
            'Turkish Angora',
            'Turkish Van',
            'Ukranian Levkoy',
            'Unknown'
        ];
        foreach ($catBreeds as $catBreed){
            $feline = new Breed;
            $feline->specie_id = 2;
            $feline->name = $catBreed;
            $feline->added_by = 1;
            $feline->save();
        }

        //Exotic
        $exoticBreads = [
            'Amphibian',
            'Avian',
            'Caprine',
            'Erinaceidea',
            'Lagomorph',
            'Lutrinae',
            'Marsupial',
            'Mephitidae',
            'Mustelid',
            'Ovine',
            'Porcine',
            'Primate',
            'Procyon',
            'Reptile',
            'Rodent - Chinchilla',
            'Rodent - Gerbil',
            'Rodent - Guinea Pig',
            'Rodent - Hamster',
            'Rodent - Mouse',
            'Rodent - Rat',
            'Rodent - Other',
            'Other Exotic'
        ];
        foreach ($exoticBreads as $exoticBread){
            $exotic = new Breed;
            $exotic->specie_id = 3;
            $exotic->name = $exoticBread;
            $exotic->added_by = 1;
            $exotic->save();
        }
    }
}